npm install --save-dev @babel/core
npm install --save-dev @babel/preset-env
npm install --save-dev coffeescript
npm install --save-dev gulp-babel
npm install --save-dev gulp-coffee
npm install --save-dev gulp-tap
npm install --save-dev gulp-uglify-es
npm install --save-dev gulp
npm install --save-dev uglify-es
npm install --save-dev zip-folder
